name: Continuous Integration of a JavaScript Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Check if package.json changed
        id: package-changed
        run: |
          git fetch origin master
          git diff --exit-code HEAD^1 HEAD package.json || echo "package.json changed" > changed.txt

      - name: Cache node_modules
        id: cache-node-modules
        if: steps.package-changed.outputs.changed != 'true'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.package-changed.outputs.changed == 'true'
        run: npm ci

      - name: Upload node_modules as artifact
        if: steps.package-changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Run tests
        run: npm test
